name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Vercel
        uses: vercel/actions/github/deploy@v1
        with:
          vercel-token: ${{ secrets.VERCEL_SECRET}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./  
          args: --prod         